export const SUBJECT_REPOSITORY = Symbol('SUBJECT_REPOSITORY');
export const TOPIC_REPOSITORY = Symbol('TOPIC_REPOSITORY');
export const CARD_REPOSITORY = Symbol('CARD_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const FLOW_BOARD_REPOSITORY = Symbol('FLOW_BOARD_REPOSITORY');
